### PR TITLE
export for type casting

### PR DESCRIPTION
**Pull request by drpym**
I have function that i need the type for. Hopefully this is ok.

### CODE REVIEW

**Comment by andywer** [comment]
Hey @drpym!

The export is fine, but the 5k lines added to the `package-lock.json`… What did you do?! 😅

**Review by andywer — CHANGES_REQUESTED** [review]
Please revert the changes to `package-lock.json` 😉

**Comment by drpym** [comment]
whoops i did a npm install and accidentally committed the changes. that was my bad.

**Review by andywer — APPROVED** [review]

**Comment by andywer** [comment]
No worries 🙂

**Comment by drpym** [comment]
@andywer *not related* I have been testing in typescript 4 and it seems ok so far. Is there anything I should look at for? so far everything seems great. also nice work.

**Comment by andywer** [comment]
Took me a second to realize what you meant. The readme still said that you need (at least) TypeScript 3. Removed that. Thanks!

**Comment by drpym** [comment]
No worries :)

**Comment by andywer** [comment]
Published as v0.5.2

**Pull request merged**
